#!/bin/bash
# uwunator
# Daniel Kogan
# 11/01/2020 


cdir="$(dirname "$0")"
cd "$(dirname "$0")"

star_insert() {
		cringe=(' *nuzzles you* ' ' *notices your bulge* ' ' *squirms* ' ' *licks lips* ' ' *wags tail* ')

echo $(($RANDOM % 5))
		}

for i in {1..10}; do
star_insert
done
for file in *.txt;  do
		echo "$file" 
		sed -i '' 's/u/uwu/g'  $file
done

